# Generated by Django 4.1 on 2022-09-02 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapi.unitmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_no', models.CharField(max_length=150)),
                ('order_date', models.CharField(max_length=500)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_desc', models.CharField(max_length=500)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapi.customermodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetailModel',
            fields=[
                ('orderdetail_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_ordered', models.CharField(max_length=200)),
                ('unit_ordered', models.CharField(max_length=20)),
                ('price_ordered', models.DecimalField(decimal_places=2, max_digits=50)),
                ('quantity_ordered', models.IntegerField()),
                ('total_amount_ordered', models.DecimalField(decimal_places=2, max_digits=50)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceryapi.ordermodel')),
            ],
        ),
    ]
