# Generated by Django 4.1 on 2022-09-28 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetailmodel',
            name='product_ordered',
        ),
        migrations.AddField(
            model_name='orderdetailmodel',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groceryapi.productmodel'),
        ),
        migrations.AlterField(
            model_name='orderdetailmodel',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groceryapi.ordermodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='product_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
