# Generated by Django 4.1 on 2022-09-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapi', '0002_remove_orderdetailmodel_product_ordered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetailmodel',
            old_name='product_id',
            new_name='prod_id',
        ),
    ]
